version: '2'

services:
    web:
        image: teuki/lilypond:latest
        ports:
            - "80:80"
        volumes:
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
            - ./api:/var/www
            - ./data:/data
        environment:
            - DOCUMENT_ROOT=public
