version: '2'

services:

    # -------------------------
    # Gateway
    # -------------------------
    gateway-web:
        image: nginx:latest
        port:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - facade-network

    # -------------------------
    # Frontend
    # -------------------------
    front-web:
        image: nginx:latest
        expose:
            - "80"
        volumes:
            - ../front/public:/public
            - ../front/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - facade-network

    # -------------------------
    # API - Facade 
    # -------------------------

    api-facade:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - cnb2lp-web
            - lilypond-web
            - midi2mp3-web
        volumes:
            - ../api/facade/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
            - facade-network
        #restart: always


    # -------------------------
    # API - Service - cnb2lp
    # -------------------------

    cnb2lp-web:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - cnb2lp-php
        volumes:
            - ../api/services/cnb2lp/api:/api
            - ../api/services/cnb2lp/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network

    cnb2lp-php:
        image: php:fpm
        volumes:
            - ../api/services/cnb2lp/api:/api
            - ../api/services/cnb2lp/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network


    # -------------------------
    # API - Service - lilypond
    # -------------------------

    lilypond-web:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - lilypond-php
        volumes:
            - ../api/services/lilypond/api:/api
            - ../api/services/lilypond/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network

    lilypond-php:
        image: php:fpm
        volumes:
            - ../api/services/lilypond/api:/api
            - ../api/services/lilypond/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network

    # -------------------------
    # API - Service - midi2mp3
    # -------------------------

    midi2mp3-web:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - midi2mp3-php
        volumes:
            - ../api/services/midi2mp3/api:/api
            - ../api/services/midi2mp3/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network

    midi2mp3-php:
        image: php:fpm
        volumes:
            - ../api/services/midi2mp3/api:/api
            - ../api/services/midi2mp3/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network
	
networks:
    api-network:
        driver: bridge
    facade-network:
        driver: bridge
