version: '2'

services:

    # -------------------------
    # Gateway
    # -------------------------
    gateway-web:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - front-web
            - api-facade
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - apifacade-network
            - front-network

    # -------------------------
    # Frontend
    # -------------------------
    front-web:
        image: nginx:latest
        expose:
            - "80"
        volumes:
            - ../front/public:/public
            - ../front/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - front-network

    # -------------------------
    # API - Facade 
    # -------------------------

    api-facade:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - cnb2lp-web
            - lilypond-web
            - midi2mp3-web
        volumes:
            - ../api/facade/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - apifacade-network
            - api-network            


    # -------------------------
    # API - Service - cnb2lp
    # -------------------------

    cnb2lp-web:
        image: nginx:latest
        expose:
            - "80"
        depends_on:
            - cnb2lp-php
        volumes:
            - ../api/services/cnb2lp/api:/api
            - ../api/services/cnb2lp/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network

    cnb2lp-php:
        image: php:fpm
        volumes:
            - ../api/services/cnb2lp/api:/api
            - ../api/services/cnb2lp/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - api-network


    # -------------------------
    # API - Service - lilypond
    # -------------------------

    lilypond-web:
        image: teuki/lilypond:latest
        expose:
            - "80"
        volumes:
            - ../api/services/lilypond/apache.conf:/etc/apache2/sites-available/000-default.conf
            - ../api/services/lilypond/api:/var/www
        environment:
            - DOCUMENT_ROOT=public
            - UID = 33
        networks:
            - api-network

    # -------------------------
    # API - Service - midi2mp3
    # -------------------------

    midi2mp3-web:
        image: teuki/midi2mp3:latest
        expose:
            - "80"
        volumes:
            - ../api/services/midi2mp3/apache.conf:/etc/apache2/sites-available/000-default.conf
            - ../api/services/midi2mp3/api:/var/www
        environment:
            - DOCUMENT_ROOT=public
            - UID=33
        networks:
            - api-network

networks:
    apifacade-network:
        driver: bridge
    api-network:
        driver: bridge
    front-network:
        driver: bridge
